### PR TITLE
Cart and wishlist page

### PR DESCRIPTION
**Pull request by kshitijthatte**
Added a cart page and a wishlist page

The cart page has a sidebar that shows price details.
Product cards on the cart page have
- quantity
- Remove button
- Add to Wishlist button

The wishlist page can be accessed from nav on the cart page.

### CODE REVIEW

**Review by siddhigate — APPROVED** [review]
I think u missed the **Place order** button in the cart page. Everything else looks good to me.

**Review by srishti-maurya — APPROVED** [review]
looks good

**Review by srishti-maurya — COMMENTED** [review]
the images aren't getting loaded in the preview from my end, you might want to cross check may be

**Comment by manojasarsa** [comment]
image

The color of decrease qty button ( - ) didn't appear properly.

**Review by manojasarsa — APPROVED** [review]
Rest looks pretty good. Nice work!

**Comment by kshitijthatte** [comment]
> I think u missed the **Place order** button in the cart page. Everything else looks good to me.

@siddhigate Thanks for pointing that out, I missed it

**Comment by kshitijthatte** [comment]
> the images aren't getting loaded in the preview from my end, you might want to cross check may be

@srishti-maurya I think it was some temporary issue with unsplash.

**Comment by kshitijthatte** [comment]
> The color of decrease qty button ( - ) didn't appear properly.

@manojasarsa I'll try to change the color for better contrast ratio

**Pull request merged**
